const $ = (s, root = document) => root.querySelector(s)
const $$ = (s, root = document) => [...root.querySelectorAll(s)]
const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 })
const precise = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 2 })
const dt = new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })
const esc = value => String(value ?? '—').replace(/[&<>'"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' })[c])
const pct = value => `${value >= 0 ? '+' : ''}${Number(value).toFixed(1)}%`
const state = { data: null, range: '1Y', trade: null, connected: false }
const routes = ['overview', 'activity', 'runs', 'about']
const route = () => routes.includes(location.hash.slice(2)) ? location.hash.slice(2) : 'overview'

function preview() {
  const series=[]; let portfolio=100, benchmark=100, invested=100
  for(let i=0;i<80;i++){ portfolio*=1.0021+Math.sin(i/5)*.003; benchmark*=1.0017+Math.sin(i/7)*.003; if(i&&i%8===0){portfolio+=10;invested+=10} series.push({portfolio,benchmark,invested}) }
  const trades=[['VTI',6],['VXUS',2.5],['BND',1.5],['VTI',8],['VXUS',2],['VTI',7]].map((x,i)=>({id:i+1,symbol:x[0],side:'buy',notional:x[1],status:'filled',occurred_at:new Date(Date.UTC(2026,6,13-i,17,2)).toISOString(),run_id:`run_2026_w${29-i}`,proposal_id:`prop_${1208-i}`}))
  const runs=[['completed','Weekly allocation completed'],['completed','Weekly allocation completed'],['held','Valuation threshold not met; cash carried forward'],['risk_rejected','Quote freshness exceeded policy boundary']].map((x,i)=>({run_id:`run_2026_w${29-i}`,cycle_key:`index_dca:2026-W${29-i}`,status:x[0],detail:x[1],started_at:new Date(Date.UTC(2026,6,13-i*7,17)).toISOString()}))
  return {preview:true,series,trades,runs,mandates:[{mandate_id:'index_dca',mode:'shadow',weekly_budget:10,universe:['VTI','VXUS','BND']}],health:{status:'ready',reasons:[],last_success_age_seconds:6840,snapshot:{unresolved_order_count:0,runs_by_status:{completed:8,held:2,risk_rejected:1}}}}
}
async function load(){ const demo=preview(); try{const r=await fetch('/api/control-plane');if(!r.ok)throw Error();const live=await r.json();state.connected=true;state.data=live.has_history?{...demo,...live,preview:true}:{...demo,health:live.health,mandates:live.mandates.length?live.mandates:demo.mandates}}catch{state.data=demo} render() }
function nav(id,icon,label){return `<a href="#/${id}" class="${route()===id?'active':''}"><i>${icon}</i>${label}</a>`}
function shell(body){return `<div class="app"><aside><a class="logo" href="#/overview"><b>E</b><span>EDGECRAFT<small>CONTROL PLANE</small></span></a><nav>${nav('overview','◫','Overview')}${nav('activity','↗','Activity')}${nav('runs','⌁','Agent runs')}${nav('about','?','How it works')}</nav><footer><span class="dot ${state.data.health.status}"></span><small>SYSTEM</small><strong>${esc(state.data.health.status)}</strong><p>LOCAL OPERATOR SURFACE<br>v0.3.0</p></footer></aside><section class="main"><header><button class="menu">☰</button><span>EDGECRAFT / ${route().toUpperCase()}</span><div><i></i>${state.connected?'LEDGER CONNECTED':'PREVIEW MODE'}<button data-refresh>↻</button><b>CB</b></div></header>${state.data.preview?'<div class="banner"><b>PREVIEW DATA</b> Performance history is illustrative until broker valuation snapshots are recorded. Operational health and ledger activity remain live.</div>':''}<main>${body}</main></section></div>`}
function head(kicker,title,copy){return `<div class="page-head"><p>${kicker}</p><h1>${title}</h1><span>${copy}</span></div>`}
function render(){const pages={overview,activity,runs,about};$('#root').innerHTML=shell(pages[route()]());bind()}
function filtered(){const a=state.data.series;return state.range==='1M'?a.slice(-5):state.range==='3M'?a.slice(-14):state.range==='1Y'?a.slice(-53):a}
function chart(points){const w=900,h=290,p=25,vals=points.flatMap(d=>[d.portfolio,d.benchmark,d.invested]),min=Math.min(...vals)*.97,max=Math.max(...vals)*1.03,x=i=>p+i*(w-p*2)/(points.length-1),y=v=>p+(max-v)*(h-p*2)/(max-min),path=k=>points.map((d,i)=>`${i?'L':'M'}${x(i)},${y(d[k])}`).join(' ');return `<svg viewBox="0 0 ${w} ${h}" aria-label="Portfolio performance against the S and P 500">${[0,.25,.5,.75,1].map(t=>`<line class="grid" x1="${p}" x2="${w-p}" y1="${p+t*(h-p*2)}" y2="${p+t*(h-p*2)}"/>`).join('')}<path class="invested" d="${path('invested')}"/><path class="benchmark" d="${path('benchmark')}"/><path class="portfolio" d="${path('portfolio')}"/></svg>`}
function stat(label,value,note){return `<article><small>${label}</small><h3>${value}</h3><span>${note}</span></article>`}
function overview(){const d=state.data,s=filtered(),first=s[0],last=s.at(-1),pr=(last.portfolio/first.portfolio-1)*100,br=(last.benchmark/first.benchmark-1)*100,m=d.mandates[0]||{};return `${head('PORTFOLIO / OVERVIEW','Good afternoon, Cole.',`Your agentic portfolio is <b>${d.health.status}</b> and operating inside its mandate.`)}<section class="hero"><article class="card performance"><div class="card-head"><div><small>AGENTIC PORTFOLIO</small><h2>${money.format(last.portfolio)}</h2><span>${pct(pr)} selected period</span></div><div class="ranges">${['1M','3M','1Y','ALL'].map(r=>`<button data-range="${r}" class="${state.range===r?'active':''}">${r}</button>`).join('')}</div></div><div class="chart">${chart(s)}</div><div class="legend"><span><i class="p"></i>Agentic portfolio <b>${pct(pr)}</b></span><span><i class="b"></i>S&amp;P 500 <b>${pct(br)}</b></span><span><i class="n"></i>Net deposits <b>${money.format(last.invested)}</b></span></div></article><div class="rail"><article class="health ${d.health.status}"><div class="orbit"><i></i></div><small>AGENT STATUS</small><h2>${d.health.status==='ready'?'Operating normally':esc(d.health.status)}</h2><p>${esc(d.health.reasons?.[0]||'All deterministic checks are passing.')}</p><dl><div><dt>MODE</dt><dd>${esc(m.mode||'shadow')}</dd></div><div><dt>OPEN ORDERS</dt><dd>${d.health.snapshot.unresolved_order_count}</dd></div><div><dt>LAST CYCLE</dt><dd>${d.health.last_success_age_seconds?Math.round(d.health.last_success_age_seconds/3600)+'h ago':'—'}</dd></div></dl></article><article class="card mandate"><small>ACTIVE MANDATE</small><h3>${esc(m.mandate_id||'index_dca')}</h3><p>Invest up to <b>${precise.format(m.weekly_budget||10)}</b> weekly across a globally diversified index portfolio.</p><div>${(m.universe||[]).map(x=>`<span>${x}</span>`).join('')}</div><a href="#/about">View mandate logic →</a></article></div></section><section class="stats">${stat('NET DEPOSITS',money.format(last.invested),'Since mandate start')}${stat('RETURN VS S&P',pct(pr-br),pr>=br?'Ahead of benchmark':'Behind benchmark')}${stat('SUCCESSFUL RUNS',d.health.snapshot.runs_by_status?.completed||d.health.snapshot.runs_by_status?.shadow_complete||0,'Audited cycles')}${stat('POLICY BLOCKS',d.health.snapshot.runs_by_status?.risk_rejected||0,'Safety working as designed')}</section><section class="lower"><article class="card"><div class="section-head"><div><small>RECENT ACTIVITY</small><h2>What the agent has done</h2></div><a href="#/activity">View all →</a></div>${activityRows(d.trades.slice(0,4))}</article><article class="card allocation"><div class="section-head"><div><small>ALLOCATION</small><h2>Current target</h2></div></div><div class="donut-row"><div class="donut"><span>3<small>FUNDS</small></span></div><div>${[['VTI','60%'],['VXUS','25%'],['BND','15%']].map(x=>`<p><b>${x[0]}</b><span>${x[1]}</span></p>`).join('')}</div></div></article></section>`}
function activityRows(items){return items.length?`<div class="activity-list">${items.map(t=>`<button data-trade="${t.id}"><i>↗</i><span><b>${esc((t.side||'event').toUpperCase())} ${esc(t.symbol||'ORDER')}</b><small>${dt.format(new Date(t.occurred_at))} · ${esc(t.status)}</small></span><strong>${t.notional?precise.format(t.notional):'—'}</strong><em>›</em></button>`).join('')}</div>`:'<div class="empty">No broker order events yet.</div>'}
function activity(){const t=state.data.trades;return `${head('AUDIT / ACTIVITY','Trading history','Inspect every order transition captured by the append-only ledger.')}<div class="filters"><span>${t.length} EVENTS</span><button>ALL</button><button>FILLED</button><button>BLOCKED</button></div><article class="card table"><table><thead><tr><th>TRADE</th><th>STATUS</th><th>TIME</th><th>RUN</th><th>NOTIONAL</th></tr></thead><tbody>${t.map(x=>`<tr data-trade="${x.id}"><td><b>${esc(x.symbol||'Order')}</b><small>${esc(x.side||'event')}</small></td><td><span class="pill">${esc(x.status)}</span></td><td>${dt.format(new Date(x.occurred_at))}</td><td><code>${esc(x.run_id?.slice(0,16))}</code></td><td>${x.notional?precise.format(x.notional):'—'}</td></tr>`).join('')}</tbody></table></article>${state.trade?drawer():''}`}
function runs(){const a=state.data.runs;return `${head('OBSERVABILITY / RUNS','Agent runs','A readable trace of every observe → decide → gate → execute → reconcile cycle.')}<section class="runs"><div>${a.map(r=>`<article class="card run"><i class="${r.status}">${r.status==='completed'?'✓':r.status==='risk_rejected'?'×':'•'}</i><div><small>${esc(r.cycle_key)}</small><h3>${esc(r.status.replaceAll('_',' '))}</h3><p>${esc(r.detail||'No operator detail recorded.')}</p></div><code>${esc(r.run_id.slice(0,18))}</code></article>`).join('')}</div><aside class="card contract"><small>CYCLE CONTRACT</small>${['Observe broker truth','Form typed decision','Apply hard policy','Issue scoped permit','Execute exact order','Reconcile + audit'].map((x,i)=>`<p><span>0${i+1}</span>${x}</p>`).join('')}</aside></section>`}
function about(){const steps=[['Mandate','You set the goal, weekly ceiling, universe, benchmark, and risk posture.'],['Observe','The agent refreshes portfolio, positions, open orders, quotes, and market context.'],['Decide','Codex proposes an invest-or-hold decision with rationale, uncertainty, and typed allocations.'],['Gate','Python checks freshness, cash, concentration, tilt, budget, confidence, and unresolved orders.'],['Execute','Shadow stops here. Live mode needs broker review plus one short-lived, single-use permit.'],['Reconcile','Broker truth is read back. Every outcome enters the audit trail.']];return `${head('ABOUT / GETTING STARTED','A model can suggest. It cannot authorize itself.','Follow one contribution through the system and see exactly where judgment ends and deterministic authority begins.')}<section class="about-hero"><div><small>THE CORE IDEA</small><h2>Reasoning with<br><em>hard edges.</em></h2></div><p>Edgecraft can study fresh evidence and choose to invest or hold, but every action must fit inside a mandate you defined and pass policy code the model cannot edit at runtime.</p></section><section class="workflow">${steps.map((s,i)=>`<article><span>0${i+1}</span><div><small>PHASE 0${i+1}</small><h3>${s[0]}</h3><p>${s[1]}</p></div><i>→</i></article>`).join('')}</section><section class="boundary"><div><small>TRUST BOUNDARY</small><h2>Three actors.<br>One narrow handoff.</h2></div><div>${[['PROBABILISTIC','Model proposes','Interprets evidence. May hold cash. Never expands its own authority.'],['DETERMINISTIC','Policy authorizes','Typed rules enforce budget, freshness, exposure, and execution limits.'],['EXTERNAL TRUTH','Broker executes','Robinhood reviews the exact order, then Edgecraft reconciles its final state.']].map((x,i)=>`${i?' <b>→</b> ':''}<article><small>${x[0]}</small><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div></section><section class="quick card"><div><small>START HERE</small><h2>Run your first safe cycle</h2><p>The example mandate is shadow-only. It can exercise the complete workflow without placing a broker order.</p></div><pre>make dev\nedgecraft mandate-validate --config examples/mandate.index-dca.json\nedgecraft cycle --mandate examples/mandate.index-dca.json --ledger state/edgecraft.db --force</pre></section>`}
function drawer(){const t=state.data.trades.find(x=>String(x.id)===String(state.trade));return `<div class="backdrop" data-close></div><aside class="drawer"><button data-close>×</button><small>TRADE INSPECTOR</small><h2>${esc(t.side?.toUpperCase())} ${esc(t.symbol)}</h2><span class="pill">${esc(t.status)}</span><dl><dt>NOTIONAL</dt><dd>${t.notional?precise.format(t.notional):'—'}</dd><dt>OCCURRED</dt><dd>${dt.format(new Date(t.occurred_at))}</dd><dt>RUN ID</dt><dd><code>${esc(t.run_id)}</code></dd><dt>PROPOSAL</dt><dd><code>${esc(t.proposal_id)}</code></dd></dl></aside>`}
function bind(){$$('[data-refresh]').forEach(x=>x.onclick=load);$$('[data-range]').forEach(x=>x.onclick=()=>{state.range=x.dataset.range;render()});$$('[data-trade]').forEach(x=>x.onclick=()=>{state.trade=x.dataset.trade;if(route()!=='activity')location.hash='#/activity';else render()});$$('[data-close]').forEach(x=>x.onclick=()=>{state.trade=null;render()});$('.menu')?.addEventListener('click',()=>$('.app>aside').classList.toggle('open'))}
window.addEventListener('hashchange',render)
load()
